kind: Service
apiVersion: v1
metadata:
  name: public-cvat-production-service
  namespace: production
spec:
  type: ExternalName
  externalName: cvat-proxy-service.cvat.svc.cluster.local
  ports:
  - port: 80
